
* GENERATING A DRUM RHYTHM
** Initial thought
   + maybe we can do some sort of hierarchical structure to handle
     different level of patterns (like general pattern against specific
     decoration pattern)
   + ESN or LSTM ?
     maybe it's better to go for the ESN, simply because the LSTM's
     methods for generating music have been already explored

** Papers

   + [[./LSTM-generation-of-music.pdf][./LSTM-generation-of-music.pdf]] this paper show how to build
     an LSTM network to generate classical music (piano)
   + [[./2561_Ivanchev2013.pdf][./2561_Ivanchev2013.pdf]] this paper used ESN for pattern
     generation in robotics (maybe it could be useful to look at how
     they design the network, etc)
   + [[./anticipation-RNN.pdf][./anticipation-RNN.pdf]] this paper introduce a "new" type of
     RNN architecture which generate music given some kind of "style"
     constraint. (can be useful for some inspiration on the structure
     of our NN)
   + [[./functional-taxonomy-of-music-gen-sys.pdf][./functional-taxonomy-of-music-gen-sys.pdf]] quite general paper
     about music generation. (the main point here can be how to
     measure performance)
   + [[./LSTM-music-generation-2020.pdf][./LSTM-music-generation-2020.pdf]] this paper show how to use LSTM
     to generate music, it tries different kind of RNN.(look at loss
     function and architecture)
   + [[./PracticalESN.pdf][./PracticalESN.pdf]] an introduction on how to use and apply
     Echo State Network (seems quite useful)
   + [[./ESN-levenberg-for-chaotic-time-series-prediction.pdf][./ESN-levenberg-for-chaotic-time-series-prediction.pdf]]
     [[./ESN-levenberg-new-method.pdf][./ESN-levenberg-new-method.pdf]] these papers illustrate a
     different technique to learn the output weights which instead of
     using a simple linear regression uses the Levenberg-Marquardt
     algorithm, it seems quite complicated math for now so maybe it's
     better to go through when we have more knowledge.
   + [[./ESN-opt-binary-grey-wolf.pdf][./ESN-opt-binary-grey-wolf.pdf]] this paper illustrate an hybrid
     ESN network called BGWO-ESN which is based on the Grey wolf
     optimization algorithm, it also compare this GWO to other
     evolutionary algorithm like GA(genetic algorithm). it shows that
     this new hybrid network has better results compared to standard
     ESN and GA-ESN on financial prediction. (it seems interesting)
   + [[./ESNTutorialRev.pdf][./ESNTutorialRev.pdf]] just a tutorial on RNN by Jaeger.
   + [[./ESN-universal.pdf][./ESN-universal.pdf]] a proof of the universality of the ESN.
   + [[./hierarchicalesn_techrep10.pdf][./hierarchicalesn_techrep10.pdf]] an example of how to do
     hierarchical ESN by Jaeger. we can get some ideas from there if
     we go for an hierarchical architecture.
   + [[./ESN-music-by-prediction.pdf][./ESN-music-by-prediction.pdf]] the bachelor thesis on nestor
     about ESN and music generation. I didnt read it but it seems useful.
